AWSTemplateFormatVersion: '2010-09-09'

Description: EC2 con CodeDeploy y Apache sin SSH


Resources:

  InstanceRole:

    Type: AWS::IAM::Role

    Properties:

      RoleName: WebAppEC2Role

      AssumeRolePolicyDocument:

        Statement:

          - Effect: Allow

            Principal:

              Service: ec2.amazonaws.com

            Action: sts:AssumeRole

      ManagedPolicyArns:

        - arn:aws:iam::aws:policy/AmazonEC2FullAccess

        - arn:aws:iam::aws:policy/AmazonS3FullAccess


  InstanceProfile:

    Type: AWS::IAM::InstanceProfile

    Properties:

      Roles:

        - !Ref InstanceRole


  WebAppInstance:

      Type: AWS::EC2::Instance

      Properties:

        InstanceType: t2.micro

        IamInstanceProfile: !Ref InstanceProfile

        ImageId: ami-0c2b8ca1dad447f8a # Amazon Linux 2 (us-east-1)

        SecurityGroups:

          - !Ref WebAppSG

        UserData:

          Fn::Base64: !Sub |

            #!/bin/bash

            yum update -y

            yum install -y ruby wget

            cd /home/ec2-user

            wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install

            chmod +x ./install

            ./install auto

            service codedeploy-agent start

            yum install -y httpd

            systemctl enable httpd

        Tags:

          - Key: Name

            Value: WebAppEC2


  WebAppSG:

    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: Web SG

      SecurityGroupIngress:

        - IpProtocol: tcp

          FromPort: 80

          ToPort: 80

          CidrIp: 0.0.0.0/0


Outputs:

  InstanceId:

    Value: !Ref WebAppInstance

  PublicIP:

    Value: !GetAtt WebAppInstance.PublicIp


